// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glsekgglwptrwoizocxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsc2VrZ2dsd3B0cndvaXpvY3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTM0MTMsImV4cCI6MjA3Mzg2OTQxM30.VROdJZ6FZJxsRbdTMry7OIQPQBKdQ6_4ZPQLI9gD1Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});